#define IDS_STATICTEXT               100
#define IDE_CHARNAME                 101
#define IDS_CLASS1                   102
#define IDC_CLASS1                   103
#define IDC_LEVEL1                   104
#define IDS_LEVEL1                   105
#define IDS_BLOODLINE                106
#define IDC_BLOODLINE                107
#define IDS_ALIGNMENT                108
#define IDC_ALIGNMENT                109
#define IDS_STRENGTH                 110
#define IDE_STRENGTH                 111
#define IDS_INTELLIGENCE             112
#define IDE_INTELLIGENCE             113
#define IDS_DEXTERITY                114
#define IDE_DEXTERITY                115
#define IDS_WISDOM                   116
#define IDE_WISDOM                   117
#define IDS_CONSTITUTION             118
#define IDE_CONSTITUTION             119
#define IDS_CHARISMA                 120
#define IDE_CHARISMA                 121
#define IDS_THAC0                    122
#define IDE_THAC0                    123
#define IDB_ROLL_STATS               124
#define IDB_ROLL_INTELLIGENCE        125
#define IDB_ROLL_DEXTERITY           126
#define IDB_ROLL_WISDOM              127
#define IDB_ROLL_CONSTITUTION        128
#define IDB_ROLL_CHARISMA            129
#define IDB_ROLL_THAC0               130
#define IDP_APPEARANCE               131
#define IDC_APPEARANCE               132
#define IDS_ARMOR                    133
#define IDC_ARMOR                    134
#define IDS_WEAPON                   135
#define IDC_WEAPON                   136
#define IDS_GOLD                     137
#define IDE_GOLD                     138
#define IDS_EXPERIENCE               139
#define IDS_BLOOD_STRENGTH           140
#define IDS_ARMOR_CLASS              141
#define IDE_ARMOR_CLASS              142
#define IDS_HIT_POINTS               143
#define IDE_HIT_POINTS               144
#define IDS_RACE                     145
#define IDC_RACE                     146
#define IDS_CLASS2                   147
#define IDC_CLASS2                   148
#define IDS_LEVEL2                   149
#define IDC_LEVEL2                   150
#define IDS_EXPERIENCE2              151
#define IDE_EXPERIENCE2              152
#define IDE_EXPERIENCE               153
#define IDB_ROLL_LEVEL1              154
#define IDB_ROLL_EXPERIENCE          155
#define IDB_ROLL_LEVEL2              156
#define IDB_ROLL_EXPERIENCE2         157
#define IDB_ROLL_RACE                158
#define IDB_ROLL_BLOODLINE           159
#define IDB_ROLL_BLOOD_STRENGTH      160
#define IDE_BLOOD_STRENGTH           161
#define IDS_TITLE                    162
#define IDC_TITLE                    163
#define IDB_LOAD                     164
#define IDB_SAVE                     165
#define IDS_ATTACKS_PER_ROUND        166
#define IDC_ATTACKS_PER_ROUND        167
#define IDB_PORT_PREV                168
#define IDB_PORT_NEXT                169
#define IDB_INVENTORY                170
#define IDS_REALM                    171
#define IDS_BLOOD_GRADE              172
#define IDC_BLOOD_GRADE              173
#define IDB_ROLL_HITPOINTS           174
#define IDS_SELECT_REALM             200
#define IDL_SELECT_REALM             201
#define IDS_SELECT_REGENT            202
#define IDL_SELECT_REGENT            203
#define IDL_SELECT_ITEMS             300
#define IDL_SELECT_MAGIC_ITEMS       301
#define IDL_SELECT_BLOOD_ABILITIES   302
#define IDL_SELECT_SPELLS            303
#define IDL_SELECT_REALM_SPELLS      304
#define IDL_LIST_ITEMS               305
#define IDL_LIST_MAGIC_ITEMS         306
#define IDL_LIST_BLOOD_ABILITIES     307
#define IDL_LIST_SPELLS              308
#define IDL_LIST_REALM_SPELLS        309
#define IDS_INV_REALM                310
#define IDS_INV_CHAR                 311
#define IDB_INV_ROLL                 312
#define IDS_SELECT_SPELLS_1          313
#define IDS_SELECT_SPELLS_2          314
#define IDS_SELECT_REALM_SPELLS_1    315
#define IDS_SELECT_REALM_SPELLS_2    316
