/* ========================================================================
   Copyright (c) 1990,1996	Synergistic Software
   All Rights Reserved
   ======================================================================== */

#ifndef _CONTEXT_HXX
#define _CONTEXT_HXX


#define H_Zoom_Button	209
#define H_Your_Party	3
#define H_WRS_Raze	247
#define H_Wizard_Spells	232
#define H_Wizard_Realm_Spells	16
#define H_Wisdom	243
#define H_Winning_the_Game	34
#define H_Winning_the_Battle	96
#define H_Web_Page	299
#define H_Weapon	163
#define H_Ward_Spell	280
#define H_War_Report	305
#define H_Vassalage	258
#define H_Using_Spells	207
#define H_Use_Button	195
#define H_UNIVERSAL_QUICK_KEYS	237
#define H_Units_and_Provinces	119
#define H_Unit_Types_and_Strengths	73
#define H_Tutorial_Game	284
#define H_Troops	309
#define H_Troop_Report	56
#define H_Troop_Movement_Cost	226
#define H_Troop_Movement	225
#define H_Troop_Icon_Descriptions	212
#define H_Tricks__Traps__and_Puzzles	173
#define H_Tributes_and_Salaries	111
#define H_Treasury	131
#define H_Trade_Routes	116
#define H_Three_Types_of_Game	32
#define H_The_Domain_Turn	33
#define H_THACO	142
#define H_Terrain_Descriptions	214
#define H_Temple_Holdings_New_Game	292
#define H_Temple_Holdings_Button	216
#define H_Temple_Holdings	100
#define H_Taxation_Roll	169
#define H_Taxation_Overview	130
#define H_Taxation	122
#define H_Tax_Levels	9
#define H_Tax_Column	104
#define H_Tax_Collected	105
#define H_Swampy_Ground	69
#define H_Swampy_Forest	67
#define H_Success_Numbers	316
#define H_Style	14
#define H_Stronghold	248
#define H_Strength	240
#define H_Status_Button	203
#define H_Stacked_Units	224
#define H_Spymaster_Report	312
#define H_Spells_Button	198
#define H_Source_Level_Potential	18
#define H_Source_Holdings_New_Game	293
#define H_Source_Holdings_Button	215
#define H_Source_Holdings	102
#define H_Shortcuts	311
#define H_Shield	118
#define H_Select_Protocol	300
#define H_Select_Game_Type	282
#define H_Select_Game_Environment	296
#define H_Select_Domains_Button	219
#define H_Select_Characters_Party	41
#define H_Select_Adventure_Site	227
#define H_Select_a_Topic	295
#define H_Seaports	199
#define H_Screen_Size	53
#define H_Scouts	260
#define H_Save_Current_Game	28
#define H_Rule_Button	160
#define H_Rugged_Hills	65
#define H_River_Divides_Field	64
#define H_River_Bank_through_Forest	61
#define H_Return_to_Game	47
#define H_Retreat	89
#define H_Reserves	86
#define H_Reports	13
#define H_Relics_of_Power	36
#define H_Regent_s_Name	139
#define H_Regent_Picture	12
#define H_Regency_Column	103
#define H_Regency	123
#define H_Reduce_Foreign_Holdings	114
#define H_Realm_Strength_Report	304
#define H_Realm_Spells	206
#define H_Realm_Spell_Button	159
#define H_Realm_Name	20
#define H_Realm_Management_Keyboard_Controls	238
#define H_Realm_Maintenance_Screens	5
#define H_Realm_Descriptions	210
#define H_Realm__Experience_Points_Table	177
#define H_realm	38
#define H_Race	11
#define H_Quit	24
#define H_Quick_Summary	283
#define H_Quick_Keys_Summary	171
#define H_Provinces_and_Holdings_Maintenance	110
#define H_Province_Taxation	126
#define H_Province_Loyalty_Continued	127
#define H_Province_Loyalty	21
#define H_Province_Levels	19
#define H_Province_Descriptions	211
#define H_Priest_Spells	233
#define H_Priest_Realm_Spells	231
#define H_Play_Full_Game	285
#define H_Pillage	115
#define H_Pikemen	262
#define H_Payroll_Maintenance_Cost	121
#define H_Payroll	107
#define H_Pay_Gold_and_Pay_Regency	120
#define H_Party_Retreat	178
#define H_Partial_Woods	70
#define H_Partial_Obstructions	72
#define H_Other_Income	106
#define H_Options	27
#define H_Open_Field	63
#define H_Occupy_Own	117
#define H_Occupied_Provinces	109
#define H_Occupation_Overview	170
#define H_Occupation	113
#define H_Number_of_Provinces	15
#define H_New_Treasury	132
#define H_Navigating_the_Map	208
#define H_Muster_Button	158
#define H_Music_and_Sound	52
#define H_Multiplayer	26
#define H_Move_Button	48
#define H_Move	75
#define H_Mouse_Controls	239
#define H_Mountainous	66
#define H_Morale	78
#define H_Monster_Table	246
#define H_Modifying_Success_Rolls	221
#define H_Missile	80
#define H_Mercenary_Irregulars	261
#define H_Mercenary_Infantry	263
#define H_Mercenary_Cavalry	264
#define H_Memorizing_Spells	205
#define H_Melee	79
#define H_Maintenance_Overview	167
#define H_Maintenance	6
#define H_Magic_on_the_Battlefield	76
#define H_Magic_Items_Button	200
#define H_Magic_Items	37
#define H_Mage_Report	57
#define H_Loyalty_Report	58
#define H_Loyalty_Change_Law_Icon	128
#define H_Local_Area_Network	298
#define H_Load_Saved_Game	30
#define H_lieutenants	42
#define H_Lieutenant_Button	156
#define H_Lieutenant_Action_Button	157
#define H_Levies	265
#define H_Level	45
#define H_Law_Holdings_New_Game	319
#define H_Law_Holdings_Button	218
#define H_Law_Holdings	99
#define H_Law_Claims	129
#define H_Knights	266
#define H_Joined_Units	222
#define H_Items_Button	197
#define H_Irregulars	267
#define H_Iron_Will	275
#define H_Investiture_Report	308
#define H_Investiture_Button	155
#define H_Inventory_Screen	192
#define H_Inventory_Information_Windows	194
#define H_Internet_Play	297
#define H_Intelligence	242
#define H_Infantry	269
#define H_Income_from_Trade_Routes	134
#define H_Income	17
#define H_How_to_Play_the_Game	290
#define H_Hot_Boxes	202
#define H_Honest_Dealing_Spell	281
#define H_Holdings_Taxation_Table	168
#define H_Holdings	97
#define H_Hold_Action_Button	154
#define H_Hit_Points	162
#define H_History_and_Atlas	289
#define H_Historical_Background	310
#define H_Help_Menu_Cancel_Button	291
#define H_Help	25
#define H_Heavily_Wooded	71
#define H_Guild_Holdings_New_Game	29
#define H_Guild_Holdings_Button	217
#define H_Guild_Holdings	101
#define H_Gold	164
#define H_Goblins	271
#define H_Gnolls	272
#define H_Give_Button	193
#define H_Getting_Started	1
#define H_General_Report	313
#define H_Game_Speed	303
#define H_Game_Settings	49
#define H_Game_Objectives_and_Key_Information	2
#define H_Free_Actions	40
#define H_Fortify_Button	153
#define H_Forge_Ley_Line_Button	147
#define H_Expert_Tutorial	324
#define H_Expert_Game_Play	322
#define H_Experience_Points_for_Domain_Actions	145
#define H_Experience_Points	176
#define H_Experience	141
#define H_Exit_Adventure_Button	187
#define H_Espionage_Button	152
#define H_Equipping_Your_Regent_and_Lieutenant	60
#define H_Elves	273
#define H_Elite_Infantry	268
#define H_Effects_of_War	223
#define H_Dwarves	274
#define H_Drop_Button	196
#define H_Done_Button_Reports	315
#define H_Done_Button_Inventory	204
#define H_Done_Button	166
#define H_Domain_Power	124
#define H_Domain_Actions	4
#define H_Dispel_Spell	277
#define H_Diplomacy_Button	151
#define H_Dexterity	241
#define H_Defense	77
#define H_Default_Cancel_Done_Buttons	54
#define H_Deep_Waters	68
#define H_Declare_War_Button	150
#define H_Danica_s_Crystal_of_Scrying	39
#define H_Creating_a_Trade_Route	133
#define H_Create_Holding_Button	149
#define H_Court_Modifier_to_Diplomacy	112
#define H_Contest_Button	148
#define H_Contents	0
#define H_Constitution	244
#define H_Commanding_a_Battle	59
#define H_Command_View	92
#define H_Combat_Camera_Views	181
#define H_Combat_and_Spell_Use	174
#define H_Class	46
#define H_Choosing_Terrain	62
#define H_Choosing_a_Realm_and_Regent	8
#define H_Chat_Box	302
#define H_Chart	82
#define H_Charisma	245
#define H_Charge	81
#define H_Characters_on_the_Battlefield	74
#define H_Character_Status	22
#define H_Character_Statistics	140
#define H_Character_Inventory	213
#define H_Change_View	189
#define H_Change_Leader	188
#define H_Chamberlain_Report	314
#define H_Challenge	317
#define H_Cavalry	270
#define H_Castles_New_Game	35
#define H_Castles	98
#define H_Castle_Costs	108
#define H_Cancel_Begin_New_Game	288
#define H_Cancel_and_Done_Buttons	228
#define H_Build_Road_Button	146
#define H_Bloodline_Strength	125
#define H_Bloodline_Level	318
#define H_Bloodline	43
#define H_Blood_Abilities_Button	201
#define H_Blood_Abilities	234
#define H_Blight_Spell	278
#define H_Bless_Land_Spell	279
#define H_Begin_Rule_Button	165
#define H_Begin_New_Game	31
#define H_Battles_Only	287
#define H_Battlefield_Grid_Interface	95
#define H_Battlefield_Concepts	94
#define H_Battle_Status	87
#define H_Battle_Settings	51
#define H_Battle_Quick_Keys_Buttons	84
#define H_Battle_Interface	83
#define H_Basic_Tutorial	294
#define H_Basic_Game_Play	320
#define H_Attack_Defend_Mode	186
#define H_Assets_Trade_Routes	250
#define H_Assets_Roads	255
#define H_Assets_Lieutenants	256
#define H_Assets_Ley_Lines	257
#define H_Assets_Fortifications	252
#define H_Assets_Armies	251
#define H_Assets	253
#define H_Army_Battles	10
#define H_Armor_Class	161
#define H_Archers	259
#define H_Anuire_Realm_Map	23
#define H_Anuire_Map_Buttons	220
#define H_Allies	306
#define H_Alliance_Report	55
#define H_Alignment	44
#define H_Agitate_Button	144
#define H_After_You_Win	136
#define H_Adventures_Only	286
#define H_Adventures	7
#define H_Adventure_Status_Bar	180
#define H_Adventure_Settings	50
#define H_Adventure_Quick_Keys_and_Buttons	172
#define H_ADVENTURE_QUICK_KEYS	236
#define H_Adventure_Portrait	185
#define H_Adventure_News_Report	307
#define H_Adventure_Message_Box	184
#define H_Adventure_Map	190
#define H_Adventure_Hot_Boxes	182
#define H_Adventure_Health_Bar	183
#define H_Adventure_Done_Button	191
#define H_Adventure_Description_Screen	230
#define H_Adventure_Completion	175
#define H_Adventure_Combat_Keyboard_Controls	235
#define H_Adventure_Button	143
#define H_Advanced_Tutorial	323
#define H_Advanced_Game_Play	321
#define H_Additional_Trade_Route_Information	135
#define H_Accessing_Atlas___Ruins_of_Empire	276
#define H_3D_Battle_Camera_Views	85
#define H_3D_Adventure_Viewing_Screen	179
        
        
#endif // _CONTEXT_HXX
