#ifndef _INVNBUTS_HXX
#define _INVNBUTS_HXX
/* ========================================================================
   Copyright (c) 1990,1995   Synergistic Software
   All Rights Reserved.
   ========================================================================
   Filename: InvnButs.hxx  -defines all the button IDs for the Inventory GUI
   Author: Wes Cumberland
   ======================================================================== */
/* ------------------------------------------------------------------------
   Defines
   ------------------------------------------------------------------------ */
#define INV_BUT_ALL       0
#define INV_BUT_TITLE     1
#define INV_BUT_DONE      2
#define INV_BUT_STATUS    3 
#define INV_BUT_DUDENAME  4
#define INV_BUT_LISTBOX   5
#define INV_BUT_MUNDANE   6 
#define INV_BUT_ARMS      7
#define INV_BUT_SPELLS    8
#define INV_BUT_MAGICITMS 9
#define INV_BUT_BLOODABLT 10
#define INV_BUT_USE       11
#define INV_BUT_DROP      12
#define INV_BUT_GIVE      13
#define INV_BUT_INFO      14
#define INV_BUT_SCROLLUP  18
#define INV_BUT_SCROLLDN  19

#define INV_BUT_SPELLBOX1 20
#define INV_BUT_SPELLBOX2 21
#define INV_BUT_SPELLBOX3 22
#define INV_BUT_SPELLBOX4 23
#define INV_BUT_SPELLBOX5 24
#define INV_BUT_SPELLBOX6 25

#define INV_BUT_LBNAME1 26
#define INV_BUT_LBNAME2 27
#define INV_BUT_LBNAME3 28
#define INV_BUT_LBNAME4 29
#define INV_BUT_LBNAME5 30
#define INV_BUT_LBNAME6 31
#define INV_BUT_LBNUMBER1 32
#define INV_BUT_LBNUMBER2 33
#define INV_BUT_LBNUMBER3 34
#define INV_BUT_LBNUMBER4 35
#define INV_BUT_LBNUMBER5 36
#define INV_BUT_LBNUMBER6 37
#define INV_BUT_LBICON1 38
#define INV_BUT_LBICON2 39
#define INV_BUT_LBICON3 40
#define INV_BUT_LBICON4 41
#define INV_BUT_LBICON5 42
#define INV_BUT_LBICON6 43
#define INV_BUT_LBPLUS1 44
#define INV_BUT_LBPLUS2 45
#define INV_BUT_LBPLUS3 46
#define INV_BUT_LBPLUS4 47  
#define INV_BUT_LBPLUS5 48  
#define INV_BUT_LBPLUS6 49
#define INV_BUT_LBMINUS1 50
#define INV_BUT_LBMINUS2 51
#define INV_BUT_LBMINUS3 52
#define INV_BUT_LBMINUS4 53
#define INV_BUT_LBMINUS5 54
#define INV_BUT_LBMINUS6 55


#define INV_BUT_HELPAST 56

#endif