#include "itemtype.hxx"


//MAP EFFECTS

LONG ItemEffects::MapHighlightEnemies(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::MapHighlightTreasure(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::MapHighlightEvil(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::MapHighlightMagic(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


LONG ItemEffects::MapHighlightTraps(LONG Combo,LONG Arg,LONG Action)
{
return 0;}
	
LONG ItemEffects::MapHighlightSecretDoors(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



LONG ItemEffects::MapTeleport(LONG Combo,LONG Arg,LONG Action)
{
return 0;}
