#include "itemtype.hxx"

//Relics of Power!
LONG ItemEffects::ChaliceOfDead(LONG Combo,LONG Arg,LONG Action)
{return 0;}


LONG ItemEffects::TomePrince(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


LONG ItemEffects::Corgandal(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


LONG ItemEffects::Danica(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::HammerOfThunder(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
LONG ItemEffects::SwordOfRoele(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::CandleOfInvocation(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}



/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::AmuletInspiration(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::BannerOfRoele(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}



/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::CrownOfCommand(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::SceptreCuiraeecn(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
LONG ItemEffects::BarazadsTools(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


LONG ItemEffects::FaelesRing(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::GavelonStaff(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::DierdriensRing(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


LONG ItemEffects::BrennasFavor(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::StateCrownAnnuire(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::EmperorsCrown(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::FaridsCoffer(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::RingOfWizardry(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::RobesOfMasses(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::RegaliaEmpire(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::SielGemLarge(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::SielGemSmall(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


LONG ItemEffects::NappolansTome(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::VaubenelsBook(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

LONG ItemEffects::TorcSplendor(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
