/* ========================================================================
   Copyright (c) 1990,1996   Synergistic Software
   All Rights Reserved.
   =======================================================================
   Filename: SpelType.cpp -Effects for Spells
   Author: Wes Cumberland
   ======================================================================== */
#include "itemtype.hxx"


LONG ItemEffects::Jump(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::Strength(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::StoneSkin(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


LONG ItemEffects::BarkSkin(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::MagicalVestement(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::Shrink(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


LONG ItemEffects::MagicMissileSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}
											
LONG ItemEffects::IceStormSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::ConeOfColdSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::ChainLightningSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::DeathSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::Blindness(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::PowerBlindSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::MeteorSwarmSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::PowerKillSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::TimeStopSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::FireStormSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

LONG ItemEffects::HolyWordSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::MapShowAll(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



LONG ItemEffects::LocateObject(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::TurnUndead(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::StoneUndead(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


LONG ItemEffects::FleshToStone(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::ResistFire(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::SpritualHammer(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


LONG ItemEffects::ProtectionFromEvil(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::Disintigrate(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::SpellImmunity(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::FlameStrike(LONG Combo,LONG Arg,LONG Action)
{
return 0;}




LONG ItemEffects::Shillelagh(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



LONG ItemEffects::GlobeInvulnerability(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::ShockingGrasp(LONG Combo,LONG Arg,LONG Action)
{
return 0;}




LONG ItemEffects::Confusion(LONG Combo,LONG Arg,LONG Action)
{
return 0;}




LONG ItemEffects::Knock(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */
LONG ItemEffects::UndeadTurn(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



//Not used.
LONG ItemEffects::ImprovedFireball(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

LONG ItemEffects::ActInfravision(LONG Combo,LONG Arg,LONG action)
{
return 0;}


LONG ItemEffects::Resurrection(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



LONG ItemEffects::WaterWalk(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

